[CK-33] Верстка страницы "Локализация"
iStartDevelopers/cubestore.kz pull request #32
Opened 2023-08-02 15:26 UTC by ra9miry

Верстка страницы "Локализация"

**Jira**

- Написал адаптивный tableView
- Сделал адаптивный UI

<img width="366" alt="Снимок экрана 2023-08-02 в 21 12 24" src="https://github.com/iStartDevelopers/cubestore.kz/assets/124175557/167f4626-34a9-4399-ab2c-3f36d4d91ba4">

2023-08-03 11:09 UTC, asimovravil requested changes
жду правок

2023-08-03 11:09 UTC, asimovravil commented on storecube-ios/Localization/LocalizationController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Локализация", for: indexPath) as! LocalizationViewCell
через guard сделай проверку

2023-08-03 11:09 UTC, asimovravil commented on storecube-ios/Localization/LocalizationController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Локализация", for: indexPath) as! LocalizationViewCell
а так же withIdentifier задаются как "cell_id", "localization_id" и тд

2023-08-04 13:01 UTC, ra9miry commented on storecube-ios/Localization/LocalizationController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Локализация", for: indexPath) as! LocalizationViewCell
исправил, временно guard не применил

2023-08-06 08:24 UTC, asimovravil approved these changes
Машина 👍

2023-08-06 08:24 UTC, merged