[CK-7] Верстка страницы "промокоды"
iStartDevelopers/cubestore.kz pull request #8
Opened 2023-07-13 16:50 UTC by ra9miry

Верстка страницы "промокоды"

JIra: https://cubestore.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-7

- Добавил UI
- Написал понятный и адаптивный код
- Создал интересные элементы в TableView

<img width="371" alt="Снимок экрана 2023-07-13 в 22 44 07" src="https://github.com/iStartDevelopers/cubestore.kz/assets/124175557/359464e6-255a-4f7a-b397-69db4260a7eb">

2023-07-13 19:21 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +
лишние пробелы

2023-07-13 19:33 UTC, asimovravil requested changes
нужны доработки

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +
лишний пробел

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +
лишний пробел

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/OffersController.swift
> +        view.backgroundColor = .white
.white -> AppColor.silver.uiColor

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/OffersController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Coupon", for: indexPath) as! CouponTableViewCell
Я забыл тебе сказать об этом, то что считается этим -> ! (force unwrap) <- является плохой практикой, лучше сделай так

        guard let cell = tableView.dequeueReusableCell(
            withIdentifier: "Coupon",
            for: indexPath
        ) as? CouponTableViewCell else {
            fatalError("Could not cast to file")
        }
        
https://www.youtube.com/watch?v=ixdswSmoJC0
https://swiftbook.ru/content/language-reference/statements/

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        addSubview(percentLabel)
[couponImageView, percentLabel, saleLabel, timeLabel, copyButton].forEach {
            view.addSubview($0)
        }

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        imageView.image = UIImage(named: "coupon")
AppImage.cube.uiImage

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 42)
label.font = UIFont(name: "Montserrat-(выбор шрифта обдумаем вместе)", size: 42)

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 28)
label.font = UIFont(name: "Montserrat-(выбор шрифта обдумаем вместе)", size: 28)

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.systemFont(ofSize: 18, weight: .light)
label.font = UIFont(name: "Montserrat-(выбор шрифта обдумаем вместе)", size: 18)

2023-07-13 19:33 UTC, asimovravil commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        button.setTitleColor(UIColor(red: 0.576, green: 0.761, blue: 0.992, alpha: 1.0), for: .normal)
AppColor.black.uiColor

2023-07-14 05:22 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +
убрал пробелы

2023-07-14 05:22 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +
убрал лишний пробел

2023-07-14 05:23 UTC, ra9miry commented on storecube-ios/Offers/OffersController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Coupon", for: indexPath) as! CouponTableViewCell
сделал правки с 55 строки по 65

2023-07-14 06:06 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        addSubview(percentLabel)
исправил

2023-07-14 06:06 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        imageView.image = UIImage(named: "coupon")
исправил

2023-07-14 06:06 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 42)
исправил

2023-07-14 06:06 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 28)
исправил

2023-07-14 06:07 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        label.font = UIFont.systemFont(ofSize: 18, weight: .light)
исправил

2023-07-14 06:07 UTC, ra9miry commented on storecube-ios/Offers/CouponTableViewCell.swift
> +        button.setTitleColor(UIColor(red: 0.576, green: 0.761, blue: 0.992, alpha: 1.0), for: .normal)
исправил

2023-07-14 06:08 UTC, asimovravil approved these changes
👍

2023-07-14 06:08 UTC, merged